version: '3.8'
services:
  test-task-api:
    build: .
    image: test-task
    container_name: notkirilov-test-task-api
    depends_on:
      - database
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./config:/auth-sso/config
      - ./migrations:/auth-sso/migrations
    command: [ "/bin/sh", "-c", "./test-task-migrator --config ./.env --migrations ./migrations && ./test-task-api --config ./.env" ]
    networks:
      - api_network

  database:
    image: postgres:latest
    container_name: test-task-db
    ports:
      - "${PORT_DB}:5432"
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${NAME_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  db_data:

networks:
  api_network:
    driver: bridge
